### ISSUE TITLE
dependency on streql

### ISSUE THREAD

**Issue by jtallieu** [bigcommerce/bigcommerce-api-python#9]
The pip install fails to install streql on python 2.7 on Windows7. It complains that it cannot find vcvarsall.bat.  I looked through the API and noticed that streql is only imported, but not used in the code.  I was able to use the api on Windows7 by removing that line in connection.py.  I don't want to have to install microsoft Visual Anything unless I have to.

**Comment by gabelimon** [comment]
@filipeteles, @svcew-dinesh if you are facing this issue remove [connection.py:213](https://github.com/bigcommerce/bigcommerce-api-python/blob/master/bigcommerce/connection.py#L213) and modify [setup.py:15](https://github.com/bigcommerce/bigcommerce-api-python/blob/master/setup.py#L15). I'll start looking into a permanent fix.

**Comment by taleinat** [comment]
See also PeterScott/streql#1

**Comment by sabotagebeats** [comment]
@gabelimon i'm still having this issue

**Comment by sabotagebeats** [comment]
After doing some research it seems that the BigCommerce dependencies require streql which is not available in windows binary which is causing install BigCommerce python library with pip to fail.

**Comment by gabelimon** [comment]
@bookernath Would you mind taking this over or passing it on to someone who will?

**Comment by sabotagebeats** [comment]
@gabelimon @bookernath I was unable to get streql to compile, and pip install bigcommerce was requiring a streql dependency. I ended up removing streql requirement from the setup.py and now I'm able to install bigcommerce. I'm still unsure why I'm unable to compile streql.

**Comment by taleinat** [comment]
`streql` fails to compile on Windows for Python 2.7 because it uses newer C syntax which is not supported by the old version of the MS C++ compiler which needs to be used to build extensions for Python 2.7 on Windows. See PeterScott/streql#1.

`streql` already has a pure-Python implementation, which is currently only used for PyPy compatibility. I've created PeterScott/streql#5 suggesting to use this as a fallback whenever compiling the C version fails. I also just finished implementing this, see taleinat/streql, and I've created a pull request for the original repo.
